name: Weekly Security Report

on:
  schedule:
    - cron: '0 2 * * 1'  # 每週一執行（台灣時間上午 10 點）
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝 Python 套件
        run: |
          pip install -r requirements.txt

      - name: 爬取新聞
        run: python scripts/fetch_news.py

      - name: 上傳最新新聞 JSON（會覆蓋舊檔案）
        uses: actions/upload-artifact@v4
        with:
          name: ithome-news  # 保持相同名稱，每次執行時自動覆蓋
          path: data/news.json
          retention-days: 7  # 可選，設定保留天數（7 天後自動刪除）

      - name: AI 總結新聞
        run: python scripts/summarize_news.py
        env:             
             GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: 上傳摘要後的新聞 JSON（會覆蓋舊檔案）
        uses: actions/upload-artifact@v4
        with:
          name: ithome-news-summary
          path: data/summaries.json
          retention-days: 7  # 可選，設定保留天數

      - name: 生成簡報
        run: python scripts/generate_slides.py

      - name: 發送通知
        run: python scripts/send_notification.py
        env:
             LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}

