name: Weekly Security Report

on:
  schedule:
    - cron: '0 0 * * 1'  # 每週一 00:00 UTC（台灣時間 08:00）執行
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write  # 允許 Actions 推送內容到倉庫

jobs:
  fetch-and-summarize-news:
    runs-on: ubuntu-latest

    steps:
      - name: 取得 Repository
        uses: actions/checkout@v4

      - name: 設置 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 Python 依賴
        run: pip install requests beautifulsoup4 groq

      - name: 抓取 iThome 資安新聞
        run: python scripts/fetch_news.py

      - name: 總結新聞（Groq API）
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python scripts/summarize_news.py

      - name: 生成 Marp 幻燈片 Markdown
        run: python scripts/generate_slides.py

      - name: 設置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安裝 Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: 轉換 Markdown 為 PDF
        run: marp data/report.md --pdf --output data/security_report.pdf

      - name: 上傳生成的數據
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: data/

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data/
          publish_branch: gh-pages
          enable_jekyll: false