name: Weekly Security Report

on:
  schedule:
    - cron: '0 2 * * 1'  # 每週一執行（台灣時間上午 10 點）
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝 Python 套件
        run: |
          pip install -r requirements.txt

      - name: 爬取新聞
        run: python scripts/fetch_news.py

      - name: AI 總結新聞
        run: python scripts/summarize_news.py

      - name: 生成簡報
        run: python scripts/generate_slides.py

      - name: 發送通知
        run: python scripts/send_notification.py
        env:
             LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}

